services:
  api:
    build: .
    command: xflow serve --config config.docker.yaml
    env_file:
      - .env
    environment:
      - RUST_LOG=xflow=info
    ports:
      - "8000:8000"
    networks:
      - default

  worker:
    build: .
    command: xflow worker --config config.docker.yaml
    env_file:
      - .env
    environment:
      - RUST_LOG=xflow=info
    networks:
      - default
